project_id: '902373'
api_token_env: CROWDIN_PERSONAL_TOKEN
files:
  - source: /src/i18n/locales/en/ui.json
    translation: /src/i18n/locales/%two_letters_code%/ui.json
  - source: /src/i18n/locales/en/game.json
    translation: /src/i18n/locales/%two_letters_code%/game.json
  - source: /src/data/systems/dnd5e2024/i18n/weapons.i18n.json
    translation: /src/data/systems/dnd5e2024/i18n/weapons.i18n.%two_letters_code%.json
  - source: /src/data/systems/dnd5e2024/i18n/spells.i18n.json
    translation: /src/data/systems/dnd5e2024/i18n/spells.i18n.%two_letters_code%.json
  - source: /src/data/systems/dnd5e2024/i18n/conditions.i18n.json
    translation: /src/data/systems/dnd5e2024/i18n/conditions.i18n.%two_letters_code%.json
  - source: /src/data/systems/dnd5e2024/i18n/classes.i18n.json
    translation: /src/data/systems/dnd5e2024/i18n/classes.i18n.%two_letters_code%.json
  - source: /src/data/systems/dnd5e2024/i18n/species.i18n.json
    translation: /src/data/systems/dnd5e2024/i18n/species.i18n.%two_letters_code%.json
  - source: /src/data/systems/dnd5e2024/i18n/backgrounds.i18n.json
    translation: /src/data/systems/dnd5e2024/i18n/backgrounds.i18n.%two_letters_code%.json
  - source: /src/data/systems/daggerheart/i18n/daggerheart.i18n.json
    translation: /src/data/systems/daggerheart/i18n/daggerheart.i18n.%two_letters_code%.json
